### ISSUE TITLE
Examples in profiles get in the way

### ISSUE THREAD

**Issue by DrRataplan** [eeditiones/jinks#15]
Right now, all apps will get serafin letters, example registers and more. Which is not needed.

This is annoying, devs should remove the data, which they might forget.  I foresee new apps with that example data actually deployed in production, and hard to track bugs, like unwanted search entries popping up.

Moreover: **It does not help that Jinks re-adds removed files on redeploy**. When a dev removes all cruft, they have to redo that on update. This may result in them only working on their app, never back-porting fixes to the profiles, benefiting everyone!

How about this (which @line-o and I came up with):

* We have (a set) of profiles holding example data, like `register-examples` or `serafin-examples`. Describing what they hold, functionally. 
* Every profile has a `${PROFILE_NAME}-example-data` profile next to it that just combines their preferred example data with the profile. Just a simple `extends` of the two, plus some config.json defaults applied. The annotate profile has a `annotate-example-data` counterpart that merges in the `graves20.xml` , plus the required config.

For demos, and show-offs, instantiate (extend) the example-data profile. If this later moves to a production app with data, just remove the example-data profile, and directly extend from the base profile, so `parallel` instead of `parallel-example-data`.

For projects where we have data already, directly instantiate (extend from) the correct profile.

How does this sound? Any thoughts?

**Comment by wolfgangmm** [comment]
All example data has been moved to the `demo-data` profile (except for the data files in the annotation profile). For production you would simply deselect `demo-data`.
